drinput <- read.csv("/Volumes/group_dv/personal/DValenzano/month-by-month/Sep2015/simul-paper/death-rate_rinput.csv", header=T, sep=',')

mfrow=c(1,1)
pdf("/Volumes/group_dv/personal/DValenzano/month-by-month/Sep2015/simul-paper/death-rate_s.pdf", width=4, height=3.2)
plot(drinput$Age, drinput$Clc_s, type="l", lwd=3)
lines(drinput$Age, drinput$Csc_s, lwd=3, lty=2)
lines(drinput$Age, drinput$Clp_s, lwd=3, col="red")
lines(drinput$Age, drinput$Csp_s, lwd=3, lty=2, col="red")
abline(v=16, lwd=1, lty=2)
dev.off()

mfrow=c(1,1)
pdf("/Volumes/group_dv/personal/DValenzano/month-by-month/Sep2015/simul-paper/death-rate_p.pdf", width=4, height=3.2)
plot(drinput$Age, drinput$Clc_as, type="l", lwd=3)
lines(drinput$Age, drinput$Csc_as, lwd=3, lty=2)
lines(drinput$Age, drinput$Clp_as, lwd=3, col="red")
lines(drinput$Age, drinput$Csp_as, lwd=3, lty=2, col="red")
abline(v=16, lwd=1, lty=2)
dev.off()
